git remote add rakhele          https://github.com/rakhele/spbetu_os_2020_8382.git          # Рочева
git remote add sinelnikovmaxim  https://github.com/sinelnikovmaxim/spbetu_os_2020_8382.git  # Синельников
git remote add snchz29          https://github.com/snchz29/spbetu_os_2020_8382.git          # Терехов
git remote add AhimasYD         https://github.com/AhimasYD/spbetu_os_2020_8382.git         # Янкин
git remote add pajecawa         https://github.com/pajecawav/spbetu_os_2020_8382.git        # Колногоров
git remote add LangerKrieg      https://github.com/LangerKrieg/spbetu_os_2020_8382.git      # Наконечная
git remote add PavelChernitsyn  https://github.com/PavelChernitsyn/spbetu_os_2020_8382.git  # Черницын
git remote add Pavel-by         https://github.com/Pavel-by/spbetu_os_2020_8382.git         # Мирончик
git remote add inoriin          https://github.com/inoriin/spbetu_os_2020_8382.git          # Чирков
git remote add ephemerno        https://github.com/ephemerno/spbetu_os_2020_8382.git        # Ефимова
git remote add alexgorderr      https://github.com/alexgorderr/spbetu_os_2020_8382.git      # Гордиенко
git remote add ershovdev        https://github.com/ershovdev/spbetu_os_2020_8382.git        # Ершов
git remote add negativename     https://github.com/negativename/spbetu_os_2020_8382.git     # Кобенко
git remote add a-kuzina         https://github.com/a-kuzina/spbetu_os_2020_8382.git         # Кузина
git remote add smotritetamptiza https://github.com/smotritetamptiza/spbetu_os_2020_8382.git # Кулачкова
git remote add nechepurenkoN    https://github.com/nechepurenkoN/spbetu_os_2020_8382.git    # Нечепуренко
git remote add Cawanik          https://github.com/Cawanik/spbetu_os_2020_8382.git          # Никитин
git remote add filtsin          https://github.com/filtsin/spbetu_os_2020_8382.git          # Фильцин
git remote add Gargamell1       https://github.com/Gargamell1/spbetu_os_2020_8382.git       # Щеглов
git remote add Anakael          https://github.com/Anakael/spbetu_os_2020_8382.git          # Щемель
